name: CatBoost Mac
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/catboost-mac.yml

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          xcode-select --install || true
          brew install autoconf automake libtool
          brew install cmake libomp
          pip install conan==1.64.1
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.15

      - name: Debugging Environment
        run: |
          echo "Printing environment variables..."
          env
          echo "Checking installed tools..."
          which gcc
          which g++
          gcc --version
          g++ --version
          which conan
          conan --version
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.15

      - name: Cache CatBoost repository
        id: cache-catboost
        uses: actions/cache@v3
        with:
          path: catboost
          key: ${{ runner.os }}-catboost-${{ hashFiles('catboost/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-catboost-
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.15

      - name: Debug Cache
        run: |
          echo "Cache key: ${{ runner.os }}-catboost-${{ hashFiles('catboost/CMakeLists.txt') }}"
          echo "Cache hit: ${{ steps.cache-catboost.outputs.cache-hit }}"
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.15

      - if: ${{ steps.cache-catboost.outputs.cache-hit != 'true' }}
        name: List the state of the directory
        continue-on-error: true
        run: ls

      - name: Clone or update CatBoost repository
        if: steps.cache-catboost.outputs.cache-hit != 'true'
        run: |
          git clone --recursive --branch v1.2.5 https://github.com/catboost/catboost
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.15

      - name: Update Cache After Clone
        if: steps.cache-catboost.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: catboost
          key: ${{ runner.os }}-catboost-${{ hashFiles('catboost/CMakeLists.txt') }}

      - name: Build Catboost
        run: |
          cd catboost
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON
          make -j4
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.15

      - name: Prepare distribution
        run: |
          cd catboost
          mkdir -p dist
          cp catboost/python-package/catboost/lib/libcatboost.dylib dist
          cp LICENSE dist/LICENSE-catboost.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: catboost-1.2.5-x86_64-darwin
          path: catboost/dist
