name: CatBoost Mac ARM64
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/catboost-mac-arm64.yml

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install cmake libomp

      - name: Clone CatBoost repository
        run: |
          git clone --recursive https://github.com/catboost/catboost
          cd catboost
          git checkout v1.0.6  # Replace with the desired version
          mkdir -p build
          cd build
          cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DOpenMP_C_FLAGS="-Xpreprocessor -fopenmp -I/opt/homebrew/opt/libomp/include" -DOpenMP_C_LIB_NAMES=omp -DOpenMP_CXX_FLAGS="-Xpreprocessor -fopenmp -I/opt/homebrew/opt/libomp/include" -DOpenMP_CXX_LIB_NAMES=omp -DOpenMP_omp_LIBRARY=/opt/homebrew/opt/libomp/lib/libomp.dylib
          make -j4

      - name: Prepare distribution
        run: |
          cd catboost
          mkdir -p dist
          cp catboost/python-package/catboost/lib/libcatboost.dylib dist
          cp LICENSE dist/LICENSE-catboost.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: catboost-1.0.6-aarch64-darwin
          path: catboost/dist
