name: CatBoost Mac ARM64
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/catboost-mac-arm64.yml

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache CatBoost repository
        id: cache-catboost
        uses: actions/cache@v3
        with:
          path: catboost
          key: ${{ runner.os }}-catboost-${{ hashFiles('catboost/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-catboost
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.15

      - name: Debug Cache
        run: |
          echo "Cache key: ${{ runner.os }}-catboost-${{ hashFiles('catboost/CMakeLists.txt') }}"
          echo "Cache hit: ${{ steps.cache-catboost.outputs.cache-hit }}"
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.15

      - name: Clone or update CatBoost repository
        if: steps.cache-catboost.outputs.cache-hit != 'true'
        with:
          cache-from: type=local,src=catboost
          cache-to: type=local,dest=catboost
        run: |
          git clone --recursive --branch v1.2.5 https://github.com/catboost/catboost
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.15

      - name: Install dependencies
        run: |
          brew install autoconf automake libtool
          brew install cmake libomp
          pip install conan==1.64.1

      - name: Debugging Environment
        run: |
          echo "Printing environment variables..."
          env
          echo "Checking installed tools..."
          which gcc
          which g++
          gcc --version
          g++ --version
          which conan
          conan --version
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.15

      - name: Build Catboost
        run: |
          cd catboost
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -DOpenMP_C_FLAGS="-Xpreprocessor -fopenmp -I/opt/homebrew/opt/libomp/include" -DOpenMP_C_LIB_NAMES=omp -DOpenMP_CXX_FLAGS="-Xpreprocessor -fopenmp -I/opt/homebrew/opt/libomp/include" -DOpenMP_CXX_LIB_NAMES=omp -DOpenMP_omp_LIBRARY=/opt/homebrew/opt/libomp/lib/libomp.dylib
          make -j4
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.15

      - name: Prepare distribution
        run: |
          cd catboost
          mkdir -p dist
          cp catboost/python-package/catboost/lib/libcatboost.dylib dist
          cp LICENSE dist/LICENSE-catboost.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: catboost-1.2.5-aarch64-darwin
          path: catboost/dist
