name: CatBoost Mac
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths:
      - .github/workflows/catboost-mac.yml

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install cmake libomp
          pip install conan==1.64.1
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.15

      - name: Clone or update CatBoost repository
        run: |
          if [ -d "catboost" ]; then
            cd catboost
            git remote update
            LOCAL=$(git rev-parse @)
            REMOTE=$(git rev-parse @{u})
            if [ $LOCAL != $REMOTE ]; then
              git reset --hard origin/master
              git pull --recurse-submodules
            fi
          else
            git clone --recursive --branch v1.2.5 https://github.com/catboost/catboost
            cd catboost
          fi
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.15

      - name: Cache CatBoost repository
        uses: actions/cache@v3
        with:
          path: catboost
          key: ${{ runner.os }}-catboost-${{ hashFiles('catboost/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-catboost-

      - name: Build Catboost
        run: |
          cd catboost
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON
          make -j4
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.15

      - name: Prepare distribution
        run: |
          cd catboost
          mkdir -p dist
          cp catboost/python-package/catboost/lib/libcatboost.dylib dist
          cp LICENSE dist/LICENSE-catboost.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: catboost-1.2.5-x86_64-darwin
          path: catboost/dist
